name: Setup Node

inputs:
  node-version:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3.0.0

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - shell: bash
      run: pnpm i --frozen-lockfile
