name: Setup Node

inputs:
  node-version:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - shell: bash
      run: pnpm i --frozen-lockfile
