name: Setup Node

inputs:
  node-version:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - shell: bash
      run: pnpm i --frozen-lockfile
