minimumReleaseAge: 10080

catalog:
  playwright: 1.63.0
  playwright-core: 1.63.0

packages:
  - packages/*

allowBuilds:
  '@swc/core': true
  esbuild: true
  lefthook: true

overrides:
  playwright-core: 'catalog:'
