name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node }}

      - run: pnpm build

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      - if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps chromium

      - run: pnpm test

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      NODE_VERSION: 20
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: pnpm lint

  pass:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - run: exit 0

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'reg-viz/storycap-testrun' && github.ref == 'refs/heads/main'
    needs: [pass]
    env:
      NODE_VERSION: 20
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: pnpm build

      - name: Creating .npmrc
        run: |
          cat << EOF > ".npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Create Release Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: pnpm release
          commit: 'chore: version packages'
